=== PeterSzakacs/TreasureScooper/core/assets/worlds/gameworld.dtd
<!ELEMENT world (htunnels, interconnections, entrances)>
<!ATTLIST world width CDATA #REQUIRED >
<!ATTLIST world height CDATA #REQUIRED >
<!ATTLIST world offsetX CDATA #REQUIRED >
<!ATTLIST world offsetY CDATA #REQUIRED >

    <!ELEMENT htunnels (ht+)>

        <!ELEMENT ht EMPTY>
        <!ATTLIST ht x CDATA #REQUIRED >
        <!ATTLIST ht y CDATA #REQUIRED >
        <!ATTLIST ht width CDATA #REQUIRED >
        <!ATTLIST ht id ID #REQUIRED >

    <!ELEMENT interconnections (ic+)>

        <!ELEMENT ic EMPTY>
        <!ATTLIST ic x CDATA #REQUIRED >
        <!ATTLIST ic from IDREF #REQUIRED >
        <!ATTLIST ic to IDREF #REQUIRED >

    <!ELEMENT entrances (entrance+)>

        <!ELEMENT entrance EMPTY>
        <!ATTLIST entrance x CDATA #REQUIRED >
        <!ATTLIST entrance y CDATA #REQUIRED >
        <!ATTLIST entrance to IDREF #REQUIRED >

=== PeterSzakacs/TreasureScooper/core/assets/worlds/world2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "gameworld.dtd">
<world width="32" height="16" offsetX="128" offsetY="128">
    <htunnels>
        <ht id="x0y1408" x="6" y="12" width="20" />
        <ht id="x0y1152" x="9" y="9" width="16" />
        <ht id="x0y896" x="0" y="7" width="28" />
        <ht id="x0y640" x="0" y="5" width="32" />
        <ht id="x0y384" x="0" y="3" width="32" />
        <ht id="x0y128" x="0" y="1" width="32" />
    </htunnels>
    <interconnections>
        <ic x="14" from="x0y1408" to="x0y1152" />
        <ic x="21" from="x0y1408" to="x0y1152" />
        <ic x="16" from="x0y1152" to="x0y896" />
        <ic x="20" from="x0y1152" to="x0y896" />
        <ic x="3" from="x0y896" to="x0y640" />
        <ic x="12" from="x0y896" to="x0y640" />
        <ic x="5" from="x0y640" to="x0y384" />
        <ic x="21" from="x0y640" to="x0y384" />
        <ic x="8" from="x0y384" to="x0y128" />
        <ic x="25" from="x0y384" to="x0y128" />
    </interconnections>
    <entrances>
        <entrance x="10" y="13" to="x0y1408" id="left"/>
    </entrances>
</world>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/worlds/spiral.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "gameworld.dtd">
<world width="32" height="16" offsetX="128" offsetY="128">
    <htunnels>
        <ht x="15" y="12" width="7" id="a_up"/>
        <ht x="10" y="1" width="12" id="a_down"/>
        <ht x="10" y="11" width="11" id="b_up"/>
        <ht x="11" y="2" width="10" id="b_down"/>
        <ht x="11" y="10" width="9" id="c_up"/>
        <ht x="12" y="3" width="8" id="c_down"/>
        <ht x="12" y="9" width="7" id="d_up"/>
        <ht x="13" y="4" width="6" id="d_down"/>
        <ht x="13" y="8" width="5" id="e_up"/>
        <ht x="14" y="5" width="4" id="e_down"/>
        <ht x="14" y="7" width="3" id="f_up"/>
        <ht x="15" y="6" width="2" id="f_down"/>
    </htunnels>
    <interconnections>
        <ic x="21" from="a_up" to="a_down"/>
        <ic x="20" from="b_up" to="b_down"/>
        <ic x="19" from="c_up" to="c_down"/>
        <ic x="18" from="d_up" to="d_down"/>
        <ic x="17" from="e_up" to="e_down"/>
        <ic x="16" from="f_up" to="f_down"/>
        <ic x="10" from="b_up" to="a_down"/>
        <ic x="11" from="c_up" to="b_down"/>
        <ic x="12" from="d_up" to="c_down"/>
        <ic x="13" from="e_up" to="d_down"/>
        <ic x="14" from="f_up" to="e_down"/>
    </interconnections>
    <entrances>
        <entrance x="15" y="13" to="a_up" id="center"/>
    </entrances>
</world>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/worlds/waterfall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "gameworld.dtd">
<world width="32" height="16" offsetX="128" offsetY="128">
    <htunnels>
        <ht x="1" y="12" width="30" id="root"/>
        <ht x="1" y="7" width="6" id="ab"/>
        <ht x="7" y="7" width="6" id="cd"/>
        <ht x="13" y="7" width="6" id="ef"/>
        <ht x="19" y="7" width="6" id="gh"/>
        <ht x="25" y="7" width="6" id="ij"/>
        <ht x="1" y="2" width="3" id="a"/>
        <ht x="4" y="2" width="3" id="b"/>
        <ht x="7" y="2" width="3" id="c"/>
        <ht x="10" y="2" width="3" id="d"/>
        <ht x="13" y="2" width="3" id="e"/>
        <ht x="16" y="2" width="3" id="f"/>
        <ht x="19" y="2" width="3" id="g"/>
        <ht x="22" y="2" width="3" id="h"/>
        <ht x="25" y="2" width="3" id="i"/>
        <ht x="28" y="2" width="3" id="j"/>
    </htunnels>
    <interconnections>
        <ic x="3" from="root" to="ab"/>
        <ic x="9" from="root" to="cd"/>
        <ic x="15" from="root" to="ef"/>
        <ic x="21" from="root" to="gh"/>
        <ic x="27" from="root" to="ij"/>
        <ic x="2" from="ab" to="a"/>
        <ic x="5" from="ab" to="b"/>
        <ic x="8" from="cd" to="c"/>
        <ic x="11" from="cd" to="d"/>
        <ic x="14" from="ef" to="e"/>
        <ic x="17" from="ef" to="f"/>
        <ic x="20" from="gh" to="g"/>
        <ic x="23" from="gh" to="h"/>
        <ic x="26" from="ij" to="i"/>
        <ic x="29" from="ij" to="j"/>
    </interconnections>
    <entrances>
        <entrance x="16" y="13" to="root" id="center"/>
    </entrances>
</world>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/worlds/irregular.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "gameworld.dtd">
<world width="32" height="16" offsetX="128" offsetY="128">
    <htunnels>
        <ht x="0" y="11" width="32" id="a_up"/>
        <ht x="0" y="1" width="32" id="a_down"/>
        <ht x="5" y="9" width="22" id="b_up"/>
        <ht x="5" y="3" width="22" id="b_down"/>
        <ht x="10" y="7" width="12" id="c_up"/>
        <ht x="10" y="5" width="12" id="c_down"/>
    </htunnels>
    <interconnections>
        <ic x="30" from="a_up" to="a_down"/>
        <ic x="6" from="b_down" to="a_down"/>
        <ic x="25" from="b_up" to="b_down"/>
        <ic x="11" from="b_up" to="c_up"/>
        <ic x="20" from="c_up" to="c_down"/>
    </interconnections>
    <entrances>
        <entrance x="1" y="13" to="a_up" id="left"/>
    </entrances>
</world>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/worlds/branching.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "gameworld.dtd">
<world width="32" height="16" offsetX="128" offsetY="128">
    <htunnels>
        <ht x="0" y="7" width="32" id="central"/>
        <ht x="0" y="12" width="14" id="top_left_a"/>
        <ht x="3" y="10" width="7" id="top_left_b"/>
        <ht x="3" y="8" width="11" id="top_left_c"/>
        <ht x="0" y="2" width="14" id="bottom_left_a"/>
        <ht x="3" y="4" width="7" id="bottom_left_b"/>
        <ht x="3" y="6" width="11" id="bottom_left_c"/>
        <ht x="18" y="12" width="14" id="top_right_a"/>
        <ht x="22" y="10" width="7" id="top_right_b"/>
        <ht x="18" y="8" width="11" id="top_right_c"/>
        <ht x="18" y="2" width="14" id="bottom_right_a"/>
        <ht x="22" y="4" width="7" id="bottom_right_b"/>
        <ht x="18" y="6" width="11" id="bottom_right_c"/>
    </htunnels>
    <interconnections>
        <ic x="0" from="top_left_a" to="central"/>
        <ic x="13" from="top_left_a" to="top_left_c"/>
        <ic x="3" from="top_left_b" to="top_left_c"/>
        <ic x="0" from="central" to="bottom_left_a"/>
        <ic x="13" from="bottom_left_c" to="bottom_left_a"/>
        <ic x="3" from="bottom_left_c" to="bottom_left_b"/>
        <ic x="31" from="top_right_a" to="central"/>
        <ic x="18" from="top_right_a" to="top_right_c"/>
        <ic x="28" from="top_right_b" to="top_right_c"/>
        <ic x="31" from="central" to="bottom_right_a"/>
        <ic x="18" from="bottom_right_c" to="bottom_right_a"/>
        <ic x="28" from="bottom_right_c" to="bottom_right_b"/>
    </interconnections>
    <entrances>
        <entrance x="15" y="13" to="central" id="center"/>
    </entrances>
</world>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/worlds/tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE world SYSTEM "gameworld.dtd">
<world width="32" height="16" offsetX="128" offsetY="128">
    <htunnels>
        <ht x="13" y="11" width="6" id="top"/>
        <ht x="12" y="9" width="4" id="level_a_left"/>
        <ht x="16" y="9" width="4" id="level_a_right"/>
        <ht x="10" y="7" width="6" id="level_b_left"/>
        <ht x="16" y="7" width="6" id="level_b_right"/>
        <ht x="8" y="5" width="8" id="level_c_left"/>
        <ht x="16" y="5" width="8" id="level_c_right"/>
        <ht x="6" y="3" width="10" id="level_d_left"/>
        <ht x="16" y="3" width="10" id="level_d_right"/>
        <ht x="4" y="1" width="12" id="level_e_left"/>
        <ht x="16" y="1" width="12" id="level_e_right"/>
    </htunnels>
    <interconnections>
        <ic x="14" from="top" to="level_a_left"/>
        <ic x="17" from="top" to="level_a_right"/>
        <ic x="13" from="level_a_left" to="level_b_left"/>
        <ic x="12" from="level_b_left" to="level_c_left"/>
        <ic x="11" from="level_c_left" to="level_d_left"/>
        <ic x="10" from="level_d_left" to="level_e_left"/>
        <ic x="18" from="level_a_right" to="level_b_right"/>
        <ic x="19" from="level_b_right" to="level_c_right"/>
        <ic x="20" from="level_c_right" to="level_d_right"/>
        <ic x="21" from="level_d_right" to="level_e_right"/>
    </interconnections>
    <entrances>
        <entrance x="15" y="13" to="top" id="center"/>
    </entrances>
</world>
