=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/scenarios/scenario.dtd
<!ELEMENT levels (level+)>

    <!ELEMENT level (player+, updater*)>
    <!ATTLIST level world CDATA #REQUIRED>

        <!ELEMENT player EMPTY>
        <!ATTLIST player id CDATA #REQUIRED>
        <!ATTLIST player entrance CDATA #REQUIRED>

        <!ELEMENT updater EMPTY>
        <!ATTLIST updater id CDATA #REQUIRED>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/scenarios/scenario2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE levels SYSTEM "scenario.dtd">
<levels>
    <level world="world1.xml">
        <player id="A" entrance="center"/>
    </level>
    <level world="world1.xml">
        <player id="B" entrance="center"/>
    </level>
    <level world="world1.xml">
        <player id="C" entrance="center"/>
    </level>
    <level world="world2.xml">
        <player id="A" entrance="left"/>
    </level>
    <level world="world2.xml">
        <player id="B" entrance="left"/>
    </level>
    <level world="world2.xml">
        <player id="C" entrance="left"/>
    </level>
    <level world="world3.xml">
        <player id="A" entrance="center"/>
        <updater id="Walls" />
    </level>
    <level world="world3.xml">
        <player id="B" entrance="center"/>
        <updater id="Walls" />
    </level>
    <level world="world3.xml">
        <player id="C" entrance="center"/>
        <updater id="Walls" />
    </level>
</levels>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/scenarios/scenario1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE levels SYSTEM "scenario.dtd">
<levels>
    <level world="world1multiplayer.xml">
        <player id="A" entrance="left" />
        <player id="B" entrance="center" />
        <player id="C" entrance="right" />
    </level>
    <level world="world2.xml">
        <player id="A" entrance="left" />
        <updater id="Walls" />
    </level>
    <level world="world3multiplayer.xml">
        <player id="A" entrance="center" />
        <player id="A" entrance="left" />
        <updater id="Enemies" />
    </level>
    <level world="world1.xml">
        <player id="A" entrance="center" />
        <updater id="Enemies" />
    </level>
    <level world="world2multiplayer.xml">
        <player id="A" entrance="left" />
        <player id="B" entrance="right" />
        <updater id="Enemies" />
        <updater id="Walls" />
    </level>
    <level world="world3.xml">
        <player id="A" entrance="center" />
        <updater id="Enemies" />
        <updater id="Walls" />
    </level>
</levels>

=== PeterSzakacs/TreasureScooper/core/assets/configurations/XML/scenarios/scenarioBasic.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE levels SYSTEM "scenario.dtd">
<levels>
    <level world="world1.xml">
        <player id="A" entrance="center"/>
    </level>
    <level world="spiral.xml">
        <player id="A" entrance="center"/>
    </level>
    <level world="irregular.xml">
        <player id="A" entrance="left"/>
    </level>
    <level world="tree.xml">
        <player id="A" entrance="center"/>
    </level>
    <level world="waterfall.xml">
        <player id="A" entrance="center"/>
    </level>
    <level world="branching.xml">
        <player id="A" entrance="center"/>
    </level>
</levels>
